### PR TITLE
improvements in the paintkit

### PR DESCRIPTION
**Pull request by FGDATA**
by @DavidBerkut

### CODE REVIEW

**Comment by soitanen** [comment]
@legoboyvdlp by the way, will you or Gabriel change sound levels in new GPWS sosunds?

**Comment by legoboyvdlp** [comment]
I'm not sure how. You have very good ears, as I do not detect any difference in volume!

**Comment by legoboyvdlp** [comment]
We will be asking for another merge later on when we have far more work done. ;)

**Comment by soitanen** [comment]
@legoboyvdlp Just check any new altitude callout with new 2500 callout. You'll hear.

**Comment by legoboyvdlp** [comment]
Ok.

**Comment by legoboyvdlp** [comment]
@soitanen, a question: I just added a change by PH-COR which ''stops a large unrealistic pitch up movement after rotation''. 

I believe that the 737-800 is very sensitive and needs small movements to the yoke -- perhaps two inches back -- on rotation. Is that correct?

Now, I have to pull back about halfway to mantain a proper climb out path according to the FD. 
I will revert this...

From your experience, how sensitive is the 737-800 to inputs?

**Comment by soitanen** [comment]
@legoboyvdlp Check my master branch, there is another coefficient right now. In reality it's often some mistake is presented between calculated CG position and actual, so even if you properly setting stabilizer for takeoff according to FCOM, you can have different behavior on takeoff (it feels like very light and sensitive or vice versa heavy). Normally you have to pull yoke on takeoff and hold it almost without releasing it up to desired pitch. Don't forget to use trim, it's one of basic principle of flying - your aircraft must be trimmed in any stable state.

**Comment by legoboyvdlp** [comment]
Thank you very much. ;)
In my experience, the 737 flies very smoothly... and powerfully, though not as much as the supreme 757!

With a light load, it's hard to beat it for performance.

I will do some merges right now from master. Stby.

**Pull request merged**
