### PR TITLE
Merge Gabriel's changes... this time properly

### PR DESCRIPTION
**Pull request by legoboyvdlp**
Hi @soitanen,
I just spent the last hour manually fixing everything up. This pull request includes the liveries made including Egypt Air, tire smoke, and the new sounds.

Many thanks for your patience,
Legoboyvdlp

@FGDATA

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
I did it all manually, and then tested. I don't note any bugs, but if there are, let me know ;)

**Comment by soitanen** [comment]
Tested sounds in simulator... They are bad. This is copy from video - it's good. But they all are at different volume levels, it's very bad. Also, 2500 reads at 1500... At ILS approach I have terrain warning.... I understand willing to help, but help must be good, not something...
Also tire smoke is emitted from center of gravity now...
Really, what do you think about this quality of contribution?

**Comment by YV3399** [comment]
@soitanen we are correcting all these mistakes  if you want help on and if you like what others clear and ready  what is trying to say is that what we are doing is totally wrong  and that nothing works    we are doing something that many people may not have done or wanted to help you

**Comment by legoboyvdlp** [comment]
@soitanen, I did not touch the terrain... the 2500 reads at 2450 for me. 

Tire smoke -- yes, I'll do that immediately.

**Comment by YV3399** [comment]
@legoboyvdlp  @soitanen  for me it is the same

**Comment by YV3399** [comment]
the 2500 reads at 2450

**Comment by YV3399** [comment]
and I made 2 flights and everything works fine

**Comment by soitanen** [comment]
Gabriel, sorry, but I really don't understand your english very well, and I
can't understand what do you mean in last message.

My point: when you make contribution, you must know, that your contribution
will not make something worse, than it is now. Sound is thing, that people
always hear on approach, and different volume levels is very bad... I have
question - did you try your sound yourself after changing wav files? It's
impossible not to hear different volumes... If you heard it, why did you
decide to move this soundset to production?

I really like when other contribute to project, but when quality of work is
good.

2016-06-18 22:22 GMT+03:00 GabrielVenezuela notifications@github.com:

**Comment by YV3399** [comment]
ok sorry for my English.  then I will review all sounds and volume  to see what you can do

**Comment by legoboyvdlp** [comment]
@soitanen, you must have very good hearing, since I don't really note anything.

@Gabriel, tienes que cambiar sonidos en audacity, yo los anadi en 737-set.xml por el mk-viii, y no por 737-sound.xml

**Comment by YV3399** [comment]
@soitanen  and do not know if I understand your question I wanted to do to help you   it's my favorite plane and I want it to be a good plane..

**Comment by YV3399** [comment]
I want to help and sorry for all the mistakes for plane soon solve everything and if you want to help improve and correct this plane

**Comment by legoboyvdlp** [comment]
@soitanen, tire smoke looking just right from here. 2500 bug found. It works whenever one is at 2480... and also at other times. Now fixed.

**Pull request merged**
