### PR TITLE
Add two fictional liveries

### PR DESCRIPTION
**Pull request by legoboyvdlp**
I don't know if you want these two, but here they are anyway, @soitanen

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
@soitanen , new aeromexico livery by @aiannuzzi99

**Comment by legoboyvdlp** [comment]
@soitanen -- fix by JWOCKY

**Comment by soitanen** [comment]
I can commit liveries, but not steering fix, because it's not fix, it's a break. From rudder pedals nose wheel  can't turn to 78 degrees, only to 7 (according to FCOM), or even 5 degrees (according to data from real aircraft). And I don't know github very well to commit only liveries and drop commit with steering.

**Comment by legoboyvdlp** [comment]
Once someone reverts that, then it will be fixed, @soitanen

**Comment by soitanen** [comment]
Ok now, merging

**Pull request merged**
