### PR TITLE
add Gabriel's changes: services, lights, contrails, liveries, etc etc

### PR DESCRIPTION
**Pull request by legoboyvdlp**
1. new effects: Engine FIRE, contrail, Gearsmoke.
2. Add new passenger views of the wings and engine and copilot.
3. Add announcements.
4. New light control dialog
5. Fix problems with landing lights.
6. Add strobes and beacons
7. add the fuel Truck.
8. Add ground services
9. Some livery improvements
10. New liveries for Avianca, Avianca Brazil, Ecuador TAME, Aerolineas Argentinas, Gol and LAN COLOMBIA.
    (Gabriel only speaks spanish, I will translate for you @soitanen :)

### CODE REVIEW

**Comment by FGDATA** [comment]
Thanks @legoboyvdlp  for doing this :dart: (spot on)

**Comment by legoboyvdlp** [comment]
@FGDATA, thanks ;)

**Comment by soitanen** [comment]
Sorry guys, don't have enough time to work with 737. I have looked into pull request quickly.
My notes: 
- things, that can be controlled via cockpit switches must be controlled via cockpit switches. This is about light control panel. And 737 doesn't have landing light on nosegear.
- new GPWS sounds - why? Some are new, some are old, but new sounds are not from Boeing... Strange addition.
- reversers - ok for now, but later I'll redo code fully.
- other cosmetics - not so interesting for me, but ok, if people wants.

**Comment by irg1** [comment]
Could you work hard on the cockpit development? It might be like the Omega's A320

**Comment by soitanen** [comment]
@irg1 No, I'm not 3D designer.

**Comment by FGDATA** [comment]
I say if possible cherry-pick the _reversers and the cosmetic changes for
now._..

OTOH the commit is a big one, and technically one cannot "cherry-pick" per
git, but needs knowledge in the inner code to know what comes and what does
not.
:S

(that's why I couldn't myself with ease)

**Comment by soitanen** [comment]
@FGDATA yes, this is why I like to commit every even small change into single commit.

**Comment by FGDATA** [comment]
I relate

**Comment by FGDATA** [comment]
yet keep in mind Gabriel stills does not master git and he has been giving
us (and lego) big dropbox changes.

**Comment by YV3399** [comment]
ok first of all I apologize for my English I think it is at least somewhat understandable.now I saw your note soitanen is right in some things I understand but it is something that is slowly improving.I like this plane and I'm putting all my time and knowledge in the, know it's not much but something I'm doing well.

**Comment by YV3399** [comment]
@soitanen you can solve all that corrected in his note,I just do what I can and for the comfort of all,the plane has no cabin.  but good flight system and AP.. I do what I can and I think the reverse work very well and GPWS soon be more real and correct some things at least sounds better than previous.lights dialogue is temporary until someone or you develop properly cabin the 737 800 anyway not to cause any problem but a benefit for pilots using this aircraft in the FG.

**Comment by legoboyvdlp** [comment]
@soitanen Soitanen, GPWS sounds sound exactly like the 737-800 video from KLM I watched, apart from MINIMUMS. Gabriel is right now editing other GPWS sounds recorded from a fixed base simulator, and it will be ready shortly.

As for the lights, that is a help for enabling lights. I will right now remove the nose gear light. Once the cockpit has light switches... which I might do... then it can be deleted, but right now there is no way to enable the lights. 

Cosmetics: yes, recommended. Just some liveries, and making the digit lights orange, like the real one. 

Reversers: what is the problem? Only the cockpit model needs to be animated. They work.

Ground services have no cockpit switch!

Please be patient with gabriel, he is doing his best, and a very good job!

**Comment by legoboyvdlp** [comment]
@soitanen  @GabrielVenezuela 
- nose landing light fixed / luz de nariz quitado
- tire smoke fixed / humo de rueda arreglado

**Comment by YV3399** [comment]
ok ya tengo algunos sonidos GPWS mas real que antes e colocado pero no suena no se si es el formato del sonido le mandare a usted pronto a ver si le acepta sonidos en mac es muy complicado aplicar sonidos [☹]  mas tarde le paso sonidos

---

De: Jonathan Redpath notifications@github.com
Enviado: viernes, 17 de junio de 2016 04:33 p.m.
Para: soitanen/737-800
Cc: GabrielVenezuela; Mention
Asunto: Re: [soitanen/737-800] add Gabriel's changes: services, lights, contrails, liveries, etc etc (#38)

@soitanenhttps://github.com/soitanen @GabrielVenezuelahttps://github.com/GabrielVenezuela
-   nose landing light fixed / luz de nariz quitado
-   tire smoke fixed / humo de rueda arreglado

**Comment by YV3399** [comment]
le mandare ahorita correcciones de sonidos GPWS ya los tenia antes pero no los nuevo suba esto para quitar esa duda de soitanen de que los sonidos algunos son iguales y otros diferente ya le envio un link con sonidos :)

---

De: Jonathan Redpath notifications@github.com
Enviado: viernes, 17 de junio de 2016 04:33 p.m.
Para: soitanen/737-800
Cc: GabrielVenezuela; Mention
Asunto: Re: [soitanen/737-800] add Gabriel's changes: services, lights, contrails, liveries, etc etc (#38)

@soitanenhttps://github.com/soitanen @GabrielVenezuelahttps://github.com/GabrielVenezuela
-   nose landing light fixed / luz de nariz quitado
-   tire smoke fixed / humo de rueda arreglado

##

**Comment by YV3399** [comment]
listo lego correcciones de GPWS listas!! aquí tiene el link confirme cuando suba al github:

http://www.4shared.com/get/p8MP-LI6ce/sonidos_GPWS_correcciones_.html
[http://static.4shared.com/icons/150x150/zip.png?ver=54220]http://www.4shared.com/get/p8MP-LI6ce/sonidos_GPWS_correcciones_.html

sonidos GPWS correccioneshttp://www.4shared.com/get/p8MP-LI6ce/sonidos_GPWS_correcciones_.html
www.4shared.com
Download, Discover, Listen to - sonidos GPWS correcciones at 4shared free online storage service

---

De: Jonathan Redpath notifications@github.com
Enviado: viernes, 17 de junio de 2016 04:33 p.m.
Para: soitanen/737-800
Cc: GabrielVenezuela; Mention
Asunto: Re: [soitanen/737-800] add Gabriel's changes: services, lights, contrails, liveries, etc etc (#38)

@soitanenhttps://github.com/soitanen @GabrielVenezuelahttps://github.com/GabrielVenezuela
-   nose landing light fixed / luz de nariz quitado
-   tire smoke fixed / humo de rueda arreglado

##

**Comment by legoboyvdlp** [comment]
Ok, very good Gabriel

**Comment by soitanen** [comment]
How about translation?
Can you say, what exactly is wrong in old GPWS sounds?

**Comment by legoboyvdlp** [comment]
They are generic sounds, and they are not quite as realistic. These new altitude sounds that Gabriel made sound nearly exactly like any 737-800 video I can find on youtube.

**Comment by soitanen** [comment]
Hm... very strange. Altitude callouts are the same. I don't mean exactly the same files, but voice is the same.

**Comment by legoboyvdlp** [comment]
Same voice, but more realistic. The old generic sounds sound very like text to speech while the new sounds sound exactly like a real one.

**Comment by legoboyvdlp** [comment]
Listen to the altitude sounds in 737-800/sounds/gpws then listen to FGDATA/Sounds/mk-vii to hear the difference. Then watch jetstreamTV 737-800 london calling... (google that!)

**Comment by soitanen** [comment]
I have over 1200 hours in 738 simulator, so I don't need to watch video,
and this is really no difference. And it could be okay, if you don't break
normal sounds... Also question of license - where did he get this sounds?

2016-06-18 18:21 GMT+03:00 Jonathan Redpath notifications@github.com:

**Comment by abcaster** [comment]
Excuse me, but I think there are far more serious problems with Gabriel's changes. 
Whilst the fuel truck implementation is quite neat (apart from that it's very fast) the distribution of less than full tanks are seriously wrong. If the Center tank is in use at all (I fly a lot of short hauls where 10-12.000 lbs of fuel is sufficient, it shouldn't be filled at all. 

Just my few копейка :-)

med venlig hilsen - kind regards - mit freundlichen Grüßen

Alex Bach Andersen
Dirigent/Music Director ved/at Helsingør Kommunale Musikskole og MGK
Kirkekorsanger ved Humlebæk Kirke
Vicedirigent for 1. Regiment/Danske Livregiment Soldaterforenings Sangkor ved Kastellet i København

Sendt fra/Sent from tel.: +45 2041 9166

**Comment by soitanen** [comment]
Hm... I didn't test it, there are additional controls? Wing tanks must be
filled first, then center tank. In my version it must be done manually.

2016-06-18 18:32 GMT+03:00 abcaster notifications@github.com:

**Comment by legoboyvdlp** [comment]
@soitanen, I don't note any 'breaking' of normal sounds. The sounds may not note difference, but _please_ listen to each sound -- Generic and 737-800 to note the difference

Generic is close, but not quite. This sound is far better.

**Comment by abcaster** [comment]
Exactly. 
That said, it's a very nice and flyable model. 

med venlig hilsen - kind regards - mit freundlichen Grüßen

Alex Bach Andersen
Dirigent/Music Director ved/at Helsingør Kommunale Musikskole og MGK
Kirkekorsanger ved Humlebæk Kirke
Vicedirigent for 1. Regiment/Danske Livregiment Soldaterforenings Sangkor ved Kastellet i København

Sendt fra/Sent from tel.: +45 2041 9166

> Den 18. jun. 2016 kl. 17.35 skrev Michael Soitanen notifications@github.com:
> 
> Hm... I didn't test it, there are additional controls? Wing tanks must be
> filled first, then center tank. In my version it must be done manually.

**Comment by legoboyvdlp** [comment]
@soitanen re licensing, they came from a youtube video, and we asked the developer before pushing. 

https://www.youtube.com/watch?v=W5Z-d1Zx02o
image

image

image

**Comment by irg1** [comment]
In my opinion we should work in systems, fdm, fmc,.... I don't like to start flightgear with the 737-800 and the aircraft is already running. I would like to start it and do the procediments for starting the aircraft like in the real life

**Comment by legoboyvdlp** [comment]
I forgot to add the THANKS file... stby.

**Comment by soitanen** [comment]
@irg1 you said "we". So everything is in your hands too. What you did for this 738?

**Comment by soitanen** [comment]
@legoboyvdlp I will not accept this pull request, so don't grow it. Can you made request with liveries, sounds?

**Comment by legoboyvdlp** [comment]
I'll do my best in a new branch.

**Comment by soitanen** [comment]
Thanks! :)

2016-06-18 20:32 GMT+03:00 Jonathan Redpath notifications@github.com:

**Comment by YV3399** [comment]
@soitanen  Guao... what thing I really do not understand anything soitanen not know what happens I thought it was a different developer kindest etc but it was not just we wanted to help but you reject all this help I hope you can achieve your project and someday be the best of all FG You can have 1200 hours of flight in real life and sabra much of 737,800 but that does not mean it can not work on this aircraft anything even wants to correct this giving thanks so good luck and continue working only see when finish or improvements achieved over this aircraft if it ends  bye

**Comment by abcaster** [comment]
I agree. But I think this needs some developers with modelling skills. 
We have a very beautiful overhead panel at the moment, but not very many buttons to push, pull or rotate. 

A functioning radar altimeter (for setting decision height) would be very welcome. 

med venlig hilsen - kind regards - mit freundlichen Grüßen

Alex Bach Andersen
Dirigent/Music Director ved/at Helsingør Kommunale Musikskole og MGK
Kirkekorsanger ved Humlebæk Kirke
Vicedirigent for 1. Regiment/Danske Livregiment Soldaterforenings Sangkor ved Kastellet i København

Sendt fra/Sent from tel.: +45 2041 9166

**Pull request closed without merging**
