### PR TITLE
Sound bugfix

### PR DESCRIPTION
**Pull request by legoboyvdlp**
I do apologize for the bother, but it worked whenever I tested it... I should have thought of this.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
Please do NOT merge yet, I have gear / flaps  sounds coming... this time tested so much that the gears and flaps fall off the virtual aircraft!

**Comment by legoboyvdlp** [comment]
@soitanen, ready to merge: bugfixes on the sounds, new landing light switches (unanimated so far... but better than none), and the new flap, gear, and rumbling sounds. Also a proper stall sound in case you decide to make the stall warning work.

Now, this time, surely there will be no errors...

**Comment by soitanen** [comment]
@legoboyvdlp I hope you are responsible for your words, but I see, that you didn't test 2500 and approaching minimums sound. And I see it even without flight test, looking only at your code. But I downloaded, tested it and now I don't have 2500 and appr mims sounds... How can I trust your words?
Gear sound - good. Flaps - I will remove it, flaps are not heared from cockpit in any case. Landing light switches - I don't see them. From log: "Failed to load file: "landinglight.ac"" Rumble sound - ok.

**Comment by legoboyvdlp** [comment]
What are you talking about, anyway? I will not be passing any more changes at all.
You can just forget about these changes, your computer is broken.
I can prove it to you... want a video?

**Comment by soitanen** [comment]
I don't need any video. Look into code. You set condition - radio altitude
equal to 2500. Chance, that radioalt will be exactly 2500 when descending
is almost 0, because we have high accuracy of calculation with numbers
after decimal point. So this condition will never happens.

2016-06-20 15:42 GMT+03:00 Jonathan Redpath notifications@github.com:

**Comment by legoboyvdlp** [comment]
Okay :S I tested three times, and each time it worked. As for landing lights... they are there.

**Comment by soitanen** [comment]
Maybe you forgot to include landinglight.ac model into commit?

2016-06-20 15:49 GMT+03:00 Jonathan Redpath notifications@github.com:

**Pull request merged**
