### PR TITLE
Fixed splashes

### PR DESCRIPTION
**Pull request by Pakistan-1**

### CODE REVIEW

**Comment by soitanen** [comment]
Dear Suleman!

Can you remove text "Screenshot by ***" from splashes? I don't like to have
this text on splashes.
Also, your pull request have many commits, which are just garbage. I will
not accept them. This increase size of git files.

Here is way of good git using:
1. Delete your current forked repo, because there is many differences
between to repos.
2. Create via web interface new fork again.
3. Clone it on your computer (git clone ...)
4. Make new branch, which you will use for new submissions
cd 737-800
git checkout -b next
5. Then make your master branch as my repo:
git checkout master
git branch -m broken
git remote add soitanen git@github.com:soitanen/737-800.git
git pull soitanen master:master
git checkout master
git push -f
6. So now master branch is copy of my work, next branch is for your
additions. When my repo will have new commits you make these commands:
git checkout master
git pull soitanen master
git checkout next
git rebase master
After this all new commits from my repository will be in your branch next
too.
7. All new commits from you must be placed in next branch. So, you make
commit, then push changes to server:
git commit -m "Message here"
git push origin
8. And last thing - is to make pull request via github's web interface to
intoduce your changes into my repo.

Important remark: if your branch have garbage commits (not accepted and you
decided not to have them in your repo), you always can create new branch
(git checkout -b branch_name) and try to have pull request from new branch
to my repo.

2015-11-15 9:25 GMT+03:00 Suleman Siddiqui notifications@github.com:

**Comment by Pakistan-1** [comment]
Understood 
Could you send in some screenshots too ?

**Comment by soitanen** [comment]
No, I'm not an artist or screenshooter, so it's not mine.

2015-11-16 5:58 GMT+03:00 Suleman Siddiqui notifications@github.com:

**Comment by Pakistan-1** [comment]
Hey I cannot remove the Screenshot By ..... text unless I get new Screenshots to replace them so :( It will take me a while to make new ones

**Comment by soitanen** [comment]
Ok, it's not question of short time.

2015-11-17 16:11 GMT+03:00 Suleman Siddiqui notifications@github.com:

**Pull request closed without merging**
