### PR TITLE
Add two new liveries, new viewpoint

### PR DESCRIPTION
**Pull request by legoboyvdlp**
I realize that you don't want the sounds @soitanen.
Is it much extra work to merge only two commits?
Relevant commits to merge are https://github.com/soitanen/737-800/commit/d565a08a956781f3f4a70db4f0a84327c4d1fc55 and       640cec3

### CODE REVIEW

**Comment by FGDATA** [comment]
@soitanen 

This pull request for Syncing remains open 
More code has come into it now

Best,
@IAHM-COL

**Comment by soitanen** [comment]
I'll take changes in viewpoint and liveries manually and later close this pull request. I will not add new sounds.

**Comment by FGDATA** [comment]
I believe I reverted those new sounds. But Legoboy insisted in adding them.

**Comment by FGDATA** [comment]
Other than that, although I prefer synced repos, even if it implies accepting and then reverting a commit, I don't have issues with you cherrypicking whatever you want from FGMEMBERS, and then I merging your branch into. --except, that way, we don't have your input in how the plane should actually look like.

**Comment by FGDATA** [comment]
@soitanen 
I reverted the new sounds again,  (@legoboyvdlp)
Now the pull request should be clean, and allow at repo syncing. 

Best,
@IAHM-COL

**Pull request merged**
